### ISSUE TITLE
fails in heroku

### ISSUE THREAD

**Issue by matti** [matti/kommando#15]
starting
/app/vendor/bundle/ruby/2.2.0/gems/kommando-0.0.4/lib/kommando.rb:40:in `eof?': Input/output error @ io_fillbuf - fd:7 /dev/pts/0 (Errno::EIO)
	from /app/vendor/bundle/ruby/2.2.0/gems/kommando-0.0.4/lib/kommando.rb:40:in `block (2 levels) in run'

**Comment by matti** [comment]
fixed.
